/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderRouteImport } from './routes/order'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicSupabaseStatusRouteImport } from './routes/api/public/supabase-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupabaseStatusRoute = ApiPublicSupabaseStatusRouteImport.update({
  id: '/api/public/supabase-status',
  path: '/api/public/supabase-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/supabase-status': typeof ApiPublicSupabaseStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/supabase-status': typeof ApiPublicSupabaseStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/supabase-status': typeof ApiPublicSupabaseStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/menu'
    | '/order'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/account/orders'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/plans'
    | '/admin/services'
    | '/admin/testimonials'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/api/public/supabase-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/menu'
    | '/order'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/account/orders'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/plans'
    | '/admin/services'
    | '/admin/testimonials'
    | '/auth/callback'
    | '/account'
    | '/admin'
    | '/api/public/supabase-status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/gallery'
    | '/menu'
    | '/order'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sign-in'
    | '/sign-up'
    | '/account/orders'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/media'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/plans'
    | '/admin/services'
    | '/admin/testimonials'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/api/public/supabase-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicSupabaseStatusRoute: typeof ApiPublicSupabaseStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/supabase-status': {
      id: '/api/public/supabase-status'
      path: '/api/public/supabase-status'
      fullPath: '/api/public/supabase-status'
      preLoaderRoute: typeof ApiPublicSupabaseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicSupabaseStatusRoute: ApiPublicSupabaseStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
